#!/bin/sh

set -u

hex() {
	LC_ALL=C printf '%s' "$1" | od -An -v -tx1 | tr -d ' \n'
}

printf 'schema\t1\n'
printf 'argc\t%s\n' "$#"
printf 'argv0_hex\t%s\n' "$(hex "$0")"

index=1
for argument in "$@"; do
	printf 'argv%s_hex\t%s\n' "$index" "$(hex "$argument")"
	index=$((index + 1))
done

printf 'cwd_hex\t%s\n' "$(hex "$(pwd -P)")"
printf 'image_env_hex\t%s\n' "$(hex "${TSTACK_S1_IMAGE-}")"
printf 'added_env_hex\t%s\n' "$(hex "${TSTACK_S1_ADDED-}")"

exit_code=${TSTACK_S1_EXIT:-0}
case $exit_code in
	'' | *[!0-9]*) exit 125 ;;
esac
if [ "$exit_code" -gt 125 ]; then
	exit 125
fi
exit "$exit_code"
